services:

  homecloud-go-api:
    build: .
    container_name: homecloud-go-api

    env_file:
      - .env

    ports:
      - "8080:8080"

    depends_on:
      - postgres
      - rabbitmq

    volumes:
      - D:/homecloud-storage:${STORAGE_PATH}

  postgres:
    image: postgres:latest
    container_name: homecloud-go-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: homecloud-go-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:

