services:

  homecloud-go-api:
    build: .
    container_name: homecloud-go-api

    env_file:
      - .env

    ports:
      - "8080:8080"

    depends_on:
      - postgres
      - rabbitmq

    volumes:
      - D:/homecloud-storage:${STORAGE_PATH}

  postgres:
    image: postgres:latest

  rabbitmq:
    image: rabbitmq:3-management
